

EX_SYMBOL: "AAPL"

MARIA_DB_USER: "quant"
MARIA_DB_PASSWD: "0710"
MARIA_DB_ADDR: "172.21.32.1"
MARIA_DB_ADDR: "192.168.219.100"
MARIA_DB_PORT: "3306"
MARIA_DB_NAME: "quantdb"

API_KEY: '52a6facc9bba04d228d0babd4c98156c'
FMP_URL: "https://financialmodelingprep.com"

TARGET_API_LIST: "target_api_list.csv"
TARGET_STOCK_LIST: "target_symbol_list.csv"

# ROOT_PATH: "D:\\dataset\\qt\\data"
# ROOT_PATH: "D:\\dataset\\qt\\2022_11"
ROOT_PATH: "E:\\qt\\data"

START_MONTH: 3 # 1, 4, 7, 10 / 2, 5, 8, 11 / 3, 6, 9, 12
START_DATE: 13
START_YEAR: "2020"
END_YEAR: "2024"

GET_FMP: "N"
STORAGE_TYPE: "PARQUET"
CREATE_VIEW: "Y"

# EVAL, RANK, AI, AVG
REPORT_LIST: [RANK, AI]
TOP_K_NUM: 500
MEMBER_CNT: 500
REBALANCE_PERIOD: 3
TOTAL_ASSET: 100000
ABSOLUTE_SCORE: 24000
RANK_PERIOD: 1000
LOG_LVL: 10 
REFERENCE_SYMBOL: [AAPL]

RUN_REGRESSION: "N"
PRINT_AI: "N"
PRINT_PLT_IN_REGRESSOR: "N"
RPERIOD: 3
TRAIN_START_YEAR: "2020"
TRAIN_END_YEAR: "2022"
TEST_START_YEAR: "2023"
TEST_END_YEAR: "2024"